# Generated by Django 4.2.6 on 2023-11-01 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("postdate", models.DateField(auto_now_add=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("business", "ビジネス"),
                            ("life", "生活"),
                            ("other", "その他"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
